application:
  name: rails7-docker
rails:
  max_threads: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  min_threads: <%= ENV['RAILS_MIN_THREADS'] || 5 %>
  port: <%= ENV['PORT'] || 3000 %>
  env: <%= ENV['RAILS_ENV'] || 'development' %>
database:
  name: <%= ENV['DATABASE_NAME']%>
  user: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>